version: '2'
services:
  web:
    build: .
    environment:
      - DBHOST=postgres
    ports:
      - "5000:5000"
    links:
      - postgres
  postgres:
    build:
      context: .
      dockerfile: DB-Dockerfile
