version: '2'
services:
  web:
    build: .
    environment:
      - DBHOST=postgres
      - DBPORT=5432
      - DBNAME=stop
      - DBUSER=stop
      - DBPASS=stop
      - DB=stop
    ports:
      - "5000:5000"
    links:
      - postgres
  postgres:
    build:
      context: .
      dockerfile: DB-Dockerfile
